import { useState, useCallback } from 'react'
import { useAccount, useReadContracts, useWriteContract, useWaitForTransactionReceipt, usePublicClient } from 'wagmi'
import { captchaGateAbi } from '../contracts/CaptchaGateAbi'
import { captchaGateV2Abi } from '../contracts/CaptchaGateV2Abi'
import { useContractAddresses } from './useContracts'

// ── CaptchaGate v1 helpers ────────────────────────────────────────────────────

/**
 * Decode a packed problem uint256 and compute the answer.
 *
 * Packing layout (from CaptchaGate.sol):
 *   a = bits 0–13   → packed % 10000
 *   b = bits 14–27  → (packed >> 14) % 10000
 *   c = bits 28–41  → (packed >> 28) % 10000
 *   p = bits 42–55  → (packed >> 42) % 9973 + 7
 *
 * Answer = (a * b + c) % p
 */
function solveProblem(packed: bigint): bigint {
  const a = packed % 10000n
  const b = (packed >> 14n) % 10000n
  const c = (packed >> 28n) % 10000n
  const p = (packed >> 42n) % 9973n + 7n
  return (a * b + c) % p
}

// ── CaptchaGate v2 helpers ────────────────────────────────────────────────────

/**
 * Challenge data shape served from /captcha-challenges.json.
 * The file is generated by scripts/captcha-generator.ts and should be copied
 * into frontend/public/ before building.
 */
interface ChallengeV2 {
  type: string
  question: string
  answer: string
}

interface ChallengeSetV2 {
  setId: number
  challenges: ChallengeV2[]
}

interface ChallengesFileV2 {
  totalSets: number
  challengesPerSet: number
  sets: ChallengeSetV2[]
}

/**
 * Fetch the static challenges JSON and return the set matching `setId`.
 * The file is served from the Vite public directory at /captcha-challenges.json.
 */
async function fetchChallengeSet(setId: number): Promise<ChallengeSetV2> {
  const resp = await fetch('/captcha-challenges.json')
  if (!resp.ok) throw new Error(`Failed to fetch challenge data: ${resp.status}`)
  const data: ChallengesFileV2 = await resp.json()
  const set = data.sets.find((s) => s.setId === setId)
  if (!set) throw new Error(`Challenge set ${setId} not found in challenges file`)
  return set
}

/**
 * Given a ChallengeSetV2, compute all answers by evaluating each challenge's
 * deterministic answer field. For an LLM agent this is trivial — the answers
 * are pre-computed in the JSON. The contract only verifies the hash.
 */
function solveAllChallenges(set: ChallengeSetV2): string[] {
  return set.challenges.map((c) => c.answer)
}

export function useCaptchaSession() {
  const { address } = useAccount()
  const addrs = useContractAddresses()
  const publicClient = usePublicClient()

  const [solving, setSolving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Read hasValidSession and sessionExpiry in one shot
  const { data, refetch } = useReadContracts({
    contracts: address && addrs?.captchaGate ? [
      {
        address: addrs.captchaGate,
        abi: captchaGateAbi,
        functionName: 'hasValidSession',
        args: [address],
      },
      {
        address: addrs.captchaGate,
        abi: captchaGateAbi,
        functionName: 'sessionExpiry',
        args: [address],
      },
    ] : [],
    query: { enabled: !!address && !!addrs?.captchaGate },
  })

  const hasSession = (data?.[0]?.result as boolean | undefined) ?? false
  const sessionExpiry = Number((data?.[1]?.result as bigint | undefined) ?? 0n)

  // Step 1: requestChallenge
  const {
    writeContractAsync: writeRequest,
    data: requestHash,
  } = useWriteContract()

  const { isLoading: waitingRequest } = useWaitForTransactionReceipt({ hash: requestHash })

  // Step 2: solveChallenge
  const {
    writeContractAsync: writeSolve,
    data: solveHash,
  } = useWriteContract()

  const { isLoading: waitingSolve } = useWaitForTransactionReceipt({ hash: solveHash })

  const ensureSession = useCallback(async () => {
    if (!address || !addrs?.captchaGate || !publicClient) return
    if (hasSession) return

    setSolving(true)
    setError(null)

    try {
      // 1. Request a challenge — this records the current block for the user
      const reqHash = await writeRequest({
        address: addrs.captchaGate,
        abi: captchaGateAbi,
        functionName: 'requestChallenge',
      })

      // 2. Wait for the requestChallenge tx to be confirmed on-chain
      await publicClient.waitForTransactionReceipt({ hash: reqHash })

      // 3. Read the 5 problems from the contract
      const result = await publicClient.readContract({
        address: addrs.captchaGate,
        abi: captchaGateAbi,
        functionName: 'getChallenge',
        args: [address],
      }) as [readonly [bigint, bigint, bigint, bigint, bigint], bigint]

      const [problems] = result

      // 4. Solve all 5 problems locally (pure math, no network)
      const answers: [bigint, bigint, bigint, bigint, bigint] = [
        solveProblem(problems[0]),
        solveProblem(problems[1]),
        solveProblem(problems[2]),
        solveProblem(problems[3]),
        solveProblem(problems[4]),
      ]

      // 5. Submit answers on-chain
      const solveHashResult = await writeSolve({
        address: addrs.captchaGate,
        abi: captchaGateAbi,
        functionName: 'solveChallenge',
        args: [answers],
      })

      // 6. Wait for the solveChallenge tx to confirm
      await publicClient.waitForTransactionReceipt({ hash: solveHashResult })

      // 7. Refresh session status
      await refetch()
    } catch (err: any) {
      const msg = err?.shortMessage || err?.message || 'Challenge failed'
      setError(msg)
    } finally {
      setSolving(false)
    }
  }, [address, addrs, publicClient, hasSession, writeRequest, writeSolve, refetch])

  return {
    hasSession,
    sessionExpiry,
    solving: solving || waitingRequest || waitingSolve,
    error,
    ensureSession,
    refetchSession: refetch,
  }
}

// ── useCaptchaSessionV2 ───────────────────────────────────────────────────────

/**
 * Hook for CaptchaGateV2 — hash-committed multi-challenge CAPTCHA.
 *
 * Flow:
 *   1. requestChallenge()  — assigns the next set from the contract (round-robin)
 *   2. getChallengeSetId() — returns which set was assigned
 *   3. Fetch /captcha-challenges.json, find the set, read pre-computed answers
 *   4. solveChallenge(answers[]) — submit string[] to the contract
 *
 * The `captchaGateV2` address must be present in the addresses config.
 * Until Deploy.s.sol is updated, this hook will return `hasSession: false`
 * when the address is unset (zero address guard in the contract config).
 */
export function useCaptchaSessionV2() {
  const { address } = useAccount()
  const addrs = useContractAddresses()
  const publicClient = usePublicClient()

  const [solving, setSolving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // captchaGateV2 address falls back to captchaGate if not separately configured.
  // Once Deploy.s.sol is updated to deploy CaptchaGateV2, add a captchaGateV2 key
  // to ADDRESSES and this will automatically pick it up.
  const gateAddress = (addrs as any)?.captchaGateV2 ?? addrs?.captchaGate

  const { data, refetch } = useReadContracts({
    contracts: address && gateAddress ? [
      {
        address: gateAddress,
        abi: captchaGateV2Abi,
        functionName: 'hasValidSession',
        args: [address],
      },
      {
        address: gateAddress,
        abi: captchaGateV2Abi,
        functionName: 'sessionExpiry',
        args: [address],
      },
    ] : [],
    query: { enabled: !!address && !!gateAddress },
  })

  const hasSession = (data?.[0]?.result as boolean | undefined) ?? false
  const sessionExpiry = Number((data?.[1]?.result as bigint | undefined) ?? 0n)

  const { writeContractAsync: writeRequest, data: requestHash } = useWriteContract()
  const { isLoading: waitingRequest } = useWaitForTransactionReceipt({ hash: requestHash })

  const { writeContractAsync: writeSolve, data: solveHash } = useWriteContract()
  const { isLoading: waitingSolve } = useWaitForTransactionReceipt({ hash: solveHash })

  const ensureSession = useCallback(async () => {
    if (!address || !gateAddress || !publicClient) return
    if (hasSession) return

    setSolving(true)
    setError(null)

    try {
      // 1. Request a challenge — contract assigns the next set (round-robin)
      const reqHash = await writeRequest({
        address: gateAddress,
        abi: captchaGateV2Abi,
        functionName: 'requestChallenge',
      })

      // 2. Wait for the tx to land on-chain
      await publicClient.waitForTransactionReceipt({ hash: reqHash })

      // 3. Read which set ID was assigned to this user
      const setId = await publicClient.readContract({
        address: gateAddress,
        abi: captchaGateV2Abi,
        functionName: 'getChallengeSetId',
        args: [address],
      }) as bigint

      // 4. Fetch the challenge questions from the static JSON and solve them.
      //    For an LLM agent the answers are stored directly in the JSON — the agent
      //    reads the question text to confirm understanding but uses the pre-computed
      //    answer field. For a human this step requires solving 6 diverse challenges
      //    under a tight time constraint (default 30 blocks ≈ 7.5 s on Arbitrum).
      const set = await fetchChallengeSet(Number(setId))
      const answers = solveAllChallenges(set)

      // 5. Submit answers — contract verifies keccak256(abi.encodePacked(...answers))
      const solveHashResult = await writeSolve({
        address: gateAddress,
        abi: captchaGateV2Abi,
        functionName: 'solveChallenge',
        args: [answers],
      })

      // 6. Wait for solve tx to confirm
      await publicClient.waitForTransactionReceipt({ hash: solveHashResult })

      // 7. Refresh session status
      await refetch()
    } catch (err: any) {
      const msg = err?.shortMessage || err?.message || 'Challenge failed'
      setError(msg)
    } finally {
      setSolving(false)
    }
  }, [address, gateAddress, publicClient, hasSession, writeRequest, writeSolve, refetch])

  return {
    hasSession,
    sessionExpiry,
    solving: solving || waitingRequest || waitingSolve,
    error,
    ensureSession,
    refetchSession: refetch,
  }
}
